const { PrismaClient } = require('../src/generated/prisma');
const logger = require('../src/utils/logger');
const prisma = new PrismaClient();

async function main() {
  logger.info('Starting database seeding...');

  // Create menu categories
  const categories = [
    { name: 'Appetizer', nameEn: 'Appetizer', nameDe: 'Vorspeisen' },
    { name: 'Dips & Toppings', nameEn: 'Dips & Toppings', nameDe: 'Dips & Toppings' },
    { name: 'Schmitzz Fritten', nameEn: 'Schmitzz Fries', nameDe: 'Schmitzz Fritten' },
    { name: 'Burgermeister-Wahl', nameEn: 'Burgermeister Selection', nameDe: 'Burgermeister-Wahl' },
    { name: 'Veggie & vegane Burger', nameEn: 'Veggie & Vegan Burgers', nameDe: 'Veggie & vegane Burger' },
    { name: 'Beilagen', nameEn: 'Sides', nameDe: 'Beilagen' },
    { name: 'Buddah Bowls', nameEn: 'Buddha Bowls', nameDe: 'Buddah Bowls' },
    { name: 'Desserts', nameEn: 'Desserts', nameDe: 'Desserts' },
    { name: 'Softdrinks & Schorlen', nameEn: 'Soft Drinks & Spritzers', nameDe: 'Softdrinks & Schorlen' },
    { name: 'Bier', nameEn: 'Beer', nameDe: 'Bier' },
    { name: 'Wein & Sekt', nameEn: 'Wine & Sparkling', nameDe: 'Wein & Sekt' },
    { name: 'Cocktails', nameEn: 'Cocktails', nameDe: 'Cocktails' },
  ];

  logger.info('Creating categories...');
  for (const category of categories) {
    const existing = await prisma.menuCategory.findFirst({
      where: { name: category.name }
    });
    if (!existing) {
      await prisma.menuCategory.create({
        data: category,
      });
    }
  }

  // Get categories with their IDs
  const appetizer = await prisma.menuCategory.findFirst({ where: { name: 'Appetizer' } });
  const dips = await prisma.menuCategory.findFirst({ where: { name: 'Dips & Toppings' } });
  const fritten = await prisma.menuCategory.findFirst({ where: { name: 'Schmitzz Fritten' } });
  const burger = await prisma.menuCategory.findFirst({ where: { name: 'Burgermeister-Wahl' } });
  const veggie = await prisma.menuCategory.findFirst({ where: { name: 'Veggie & vegane Burger' } });
  const beilagen = await prisma.menuCategory.findFirst({ where: { name: 'Beilagen' } });
  const bowls = await prisma.menuCategory.findFirst({ where: { name: 'Buddah Bowls' } });
  const desserts = await prisma.menuCategory.findFirst({ where: { name: 'Desserts' } });
  const drinks = await prisma.menuCategory.findFirst({ where: { name: 'Softdrinks & Schorlen' } });
  const bier = await prisma.menuCategory.findFirst({ where: { name: 'Bier' } });
  const wein = await prisma.menuCategory.findFirst({ where: { name: 'Wein & Sekt' } });
  const cocktails = await prisma.menuCategory.findFirst({ where: { name: 'Cocktails' } });

  // Schmitzz Menu Items
  const menuItems = [
    // APPETIZER
    {
      name: 'Falafel',
      nameEn: 'Falafel',
      nameDe: 'Falafel',
      description: 'Knusprige Falafel',
      descriptionEn: 'Crispy falafel',
      descriptionDe: 'Knusprige Falafel',
      price: 8.80,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1608039829574-6fff1e77c648?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Onion Flower',
      nameEn: 'Onion Flower',
      nameDe: 'Zwiebelblume',
      description: 'Knusprig frittierte Zwiebelblume',
      descriptionEn: 'Crispy fried onion flower',
      descriptionDe: 'Knusprig frittierte Zwiebelblume',
      price: 4.70,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1505575967455-40e256f73376?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Mozzarella Sticks',
      nameEn: 'Mozzarella Sticks',
      nameDe: 'Mozzarella Sticks',
      description: 'Knusprig panierte Mozzarella Sticks',
      descriptionEn: 'Crispy breaded mozzarella sticks',
      descriptionDe: 'Knusprig panierte Mozzarella Sticks',
      price: 5.40,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Tortilla Wrap mit Steak',
      nameEn: 'Tortilla Wrap with Steak',
      nameDe: 'Tortilla Wrap mit Steak',
      description: 'Mit Salat, Guacamole und 120g Steak',
      descriptionEn: 'With salad, guacamole and 120g steak',
      descriptionDe: 'Mit Salat, Guacamole und 120g Steak',
      price: 9.70,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80',
    },
    {
      name: 'Tortilla Wrap mit Hähnchen',
      nameEn: 'Tortilla Wrap with Chicken',
      nameDe: 'Tortilla Wrap mit Hähnchen',
      description: 'Mit Salat, Guacamole und 120g Hähnchen',
      descriptionEn: 'With salad, guacamole and 120g chicken',
      descriptionDe: 'Mit Salat, Guacamole und 120g Hähnchen',
      price: 9.70,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1540206351-d6465b3ac1ad?w=800&q=80',
    },
    {
      name: 'Tortilla Wrap mit Falafel',
      nameEn: 'Tortilla Wrap with Falafel',
      nameDe: 'Tortilla Wrap mit Falafel',
      description: 'Mit Salat, Guacamole und Falafel',
      descriptionEn: 'With salad, guacamole and falafel',
      descriptionDe: 'Mit Salat, Guacamole und Falafel',
      price: 8.70,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'BBQ Wings',
      nameEn: 'BBQ Wings',
      nameDe: 'BBQ Wings',
      description: '5 Stück knusprige Chicken Wings',
      descriptionEn: '5 pieces of crispy chicken wings',
      descriptionDe: '5 Stück knusprige Chicken Wings',
      price: 6.20,
      categoryId: appetizer.id,
      imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=800&q=80',
    },

    // DIPS & TOPPINGS
    {
      name: 'Aioli',
      nameEn: 'Aioli',
      nameDe: 'Aioli',
      description: 'Knoblauch-Mayonnaise',
      descriptionEn: 'Garlic mayonnaise',
      descriptionDe: 'Knoblauch-Mayonnaise',
      price: 1.40,
      categoryId: dips.id,
      imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'BBQ Sauce',
      nameEn: 'BBQ Sauce',
      nameDe: 'BBQ Sauce',
      description: 'Rauchige Barbecue-Sauce',
      descriptionEn: 'Smoky barbecue sauce',
      descriptionDe: 'Rauchige Barbecue-Sauce',
      price: 1.40,
      categoryId: dips.id,
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Guacamole',
      nameEn: 'Guacamole',
      nameDe: 'Guacamole',
      description: 'Frische Avocado-Creme',
      descriptionEn: 'Fresh avocado cream',
      descriptionDe: 'Frische Avocado-Creme',
      price: 2.20,
      categoryId: dips.id,
      imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Whiskey-Sauce',
      nameEn: 'Whiskey Sauce',
      nameDe: 'Whiskey-Sauce',
      description: 'Hauseigene Whiskey-Sauce',
      descriptionEn: 'House-made whiskey sauce',
      descriptionDe: 'Hauseigene Whiskey-Sauce',
      price: 2.20,
      categoryId: dips.id,
      imageUrl: 'https://images.unsplash.com/photo-1460306855393-0410f61241c7?w=800&q=80',
    },
    {
      name: 'Sour Cream',
      nameEn: 'Sour Cream',
      nameDe: 'Sour Cream',
      description: 'Kräutersauerrahm',
      descriptionEn: 'Herb sour cream',
      descriptionDe: 'Kräutersauerrahm',
      price: 1.40,
      categoryId: dips.id,
      imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Burgersauce',
      nameEn: 'Burger Sauce',
      nameDe: 'Burgersauce',
      description: 'Hauseigene Burgersauce',
      descriptionEn: 'House-made burger sauce',
      descriptionDe: 'Hauseigene Burgersauce',
      price: 1.40,
      categoryId: dips.id,
      imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80',
      isVegetarian: true,
    },

    // SCHMITZZ FRITTEN
    {
      name: 'Chili & Carne Fritten',
      nameEn: 'Chili & Carne Fries',
      nameDe: 'Chili & Carne Fritten',
      description: '300g Schmitzz Fritten mit Chili con Carne, Käse-Sauce & Sour Cream',
      descriptionEn: '300g Schmitzz fries with chili con carne, cheese sauce & sour cream',
      descriptionDe: '300g Schmitzz Fritten mit Chili con Carne, Käse-Sauce & Sour Cream',
      price: 9.80,
      categoryId: fritten.id,
      imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=800&q=80',
    },
    {
      name: 'TexMex Fritten',
      nameEn: 'TexMex Fries',
      nameDe: 'TexMex Fritten',
      description: '300g Schmitzz Fritten mit Guacamole, Sour Cream und Tomaten-Salsa',
      descriptionEn: '300g Schmitzz fries with guacamole, sour cream and tomato salsa',
      descriptionDe: '300g Schmitzz Fritten mit Guacamole, Sour Cream und Tomaten-Salsa',
      price: 7.80,
      categoryId: fritten.id,
      imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Berliner Currywurst Fritten',
      nameEn: 'Berlin Currywurst Fries',
      nameDe: 'Berliner Currywurst Fritten',
      description: '300g Schmitzz Fritten mit Currywurstscheiben und Currysauce',
      descriptionEn: '300g Schmitzz fries with curry sausage slices and curry sauce',
      descriptionDe: '300g Schmitzz Fritten mit Currywurstscheiben und Currysauce',
      price: 8.70,
      categoryId: fritten.id,
      imageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80',
    },
    {
      name: 'Pulled Pork Fritten',
      nameEn: 'Pulled Pork Fries',
      nameDe: 'Pulled Pork Fritten',
      description: '300g Schmitzz Fritten mit Pulled Pork, Coleslaw und Sour Cream',
      descriptionEn: '300g Schmitzz fries with pulled pork, coleslaw and sour cream',
      descriptionDe: '300g Schmitzz Fritten mit Pulled Pork, Coleslaw und Sour Cream',
      price: 9.80,
      categoryId: fritten.id,
      imageUrl: 'https://images.unsplash.com/photo-1514517220017-8ce97aa164bf?w=800&q=80',
    },
    {
      name: 'Chili-Cheese Fritten',
      nameEn: 'Chili-Cheese Fries',
      nameDe: 'Chili-Cheese Fritten',
      description: '300g Schmitzz Fritten mit Chili-Cheese-Sauce und Sour Cream',
      descriptionEn: '300g Schmitzz fries with chili-cheese sauce and sour cream',
      descriptionDe: '300g Schmitzz Fritten mit Chili-Cheese-Sauce und Sour Cream',
      price: 7.80,
      categoryId: fritten.id,
      imageUrl: 'https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=800&q=80',
      isVegetarian: true,
    },

    // BURGERMEISTER-WAHL
    {
      name: 'Say Cheese Schmitzz',
      nameEn: 'Say Cheese Schmitzz',
      nameDe: 'Say Cheese Schmitzz',
      description: '200g Rindfleisch, Burgersauce, Salat, Emmentaler, Cheddar, Tomate, Gurke',
      descriptionEn: '200g beef, burger sauce, lettuce, Emmentaler, cheddar, tomato, cucumber',
      descriptionDe: '200g Rindfleisch, Burgersauce, Salat, Emmentaler, Cheddar, Tomate, Gurke',
      price: 9.90,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    },
    {
      name: 'Say Nothing Schmitzz',
      nameEn: 'Say Nothing Schmitzz',
      nameDe: 'Say Nothing Schmitzz',
      description: '200g Rindfleisch, Burgersauce, Salat, Tomate, Essiggurke, rote Zwiebeln',
      descriptionEn: '200g beef, burger sauce, lettuce, tomato, pickles, red onions',
      descriptionDe: '200g Rindfleisch, Burgersauce, Salat, Tomate, Essiggurke, rote Zwiebeln',
      price: 8.90,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    },
    {
      name: 'Cheese Lover',
      nameEn: 'Cheese Lover',
      nameDe: 'Cheese Lover',
      description: '200g Rindfleisch, doppelt Käse, Käsesauce, Röstzwiebeln',
      descriptionEn: '200g beef, double cheese, cheese sauce, fried onions',
      descriptionDe: '200g Rindfleisch, doppelt Käse, Käsesauce, Röstzwiebeln',
      price: 10.40,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=80',
    },
    {
      name: 'Der Burgermeister',
      nameEn: 'The Burgermeister',
      nameDe: 'Der Burgermeister',
      description: '200g Rindfleisch, Burgersauce, Salat, Emmentaler, Bacon, Spiegelei',
      descriptionEn: '200g beef, burger sauce, lettuce, Emmentaler, bacon, fried egg',
      descriptionDe: '200g Rindfleisch, Burgersauce, Salat, Emmentaler, Bacon, Spiegelei',
      price: 12.30,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&q=80',
    },
    {
      name: 'Burgerholic',
      nameEn: 'Burgerholic',
      nameDe: 'Burgerholic',
      description: '200g Rindfleisch, Whiskey-Sauce, Cheddar, Bacon, Röstzwiebeln',
      descriptionEn: '200g beef, whiskey sauce, cheddar, bacon, fried onions',
      descriptionDe: '200g Rindfleisch, Whiskey-Sauce, Cheddar, Bacon, Röstzwiebeln',
      price: 15.70,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=800&q=80',
    },
    {
      name: 'Pulled Pork Burger',
      nameEn: 'Pulled Pork Burger',
      nameDe: 'Pulled Pork Burger',
      description: '200g Pulled Pork, BBQ-Sauce, Lollo Bianco Salat, Coleslaw',
      descriptionEn: '200g pulled pork, BBQ sauce, Lollo Bianco lettuce, coleslaw',
      descriptionDe: '200g Pulled Pork, BBQ-Sauce, Lollo Bianco Salat, Coleslaw',
      price: 15.70,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800&q=80',
    },
    {
      name: 'Burger 202',
      nameEn: 'Burger 202',
      nameDe: 'Burger 202',
      description: '200g Rindfleisch, Burgersauce, BBQ-Sauce, doppelt Bacon, Käse',
      descriptionEn: '200g beef, burger sauce, BBQ sauce, double bacon, cheese',
      descriptionDe: '200g Rindfleisch, Burgersauce, BBQ-Sauce, doppelt Bacon, Käse',
      price: 17.60,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&q=80',
    },
    {
      name: 'Obere Burger',
      nameEn: 'Upper Burger',
      nameDe: 'Obere Burger',
      description: '400g Rindfleisch, Burgersauce, Salat, Emmentaler, Bacon',
      descriptionEn: '400g beef, burger sauce, lettuce, Emmentaler, bacon',
      descriptionDe: '400g Rindfleisch, Burgersauce, Salat, Emmentaler, Bacon',
      price: 19.40,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&q=80',
    },
    {
      name: 'Der Oberburgermeister',
      nameEn: 'The Supreme Burgermeister',
      nameDe: 'Der Oberburgermeister',
      description: '600g Rindfleisch, Burgersauce, Cheddar, Bacon, Röstzwiebeln',
      descriptionEn: '600g beef, burger sauce, cheddar, bacon, fried onions',
      descriptionDe: '600g Rindfleisch, Burgersauce, Cheddar, Bacon, Röstzwiebeln',
      price: 22.40,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    },
    {
      name: 'Omas Grilled Hähnchen Burger',
      nameEn: "Grandma's Grilled Chicken Burger",
      nameDe: 'Omas Grilled Hähnchen Burger',
      description: '200g Hähnchenbrust, Teriyakimayonnaise, Lollo Bianco Salat',
      descriptionEn: '200g chicken breast, teriyaki mayonnaise, Lollo Bianco lettuce',
      descriptionDe: '200g Hähnchenbrust, Teriyakimayonnaise, Lollo Bianco Salat',
      price: 11.80,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800&q=80',
    },
    {
      name: 'Der Fishtown Burger',
      nameEn: 'The Fishtown Burger',
      nameDe: 'Der Fishtown Burger',
      description: '200g Fischpatty, Sour Cream, Friséesalat, Tomate',
      descriptionEn: '200g fish patty, sour cream, frisée lettuce, tomato',
      descriptionDe: '200g Fischpatty, Sour Cream, Friséesalat, Tomate',
      price: 12.30,
      categoryId: burger.id,
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80',
    },

    // VEGGIE & VEGANE BURGER
    {
      name: 'Die Zicke',
      nameEn: 'The Goat',
      nameDe: 'Die Zicke',
      description: '200g veganes Patty, gebratener Ziegenkäse, Friséesalat',
      descriptionEn: '200g vegan patty, fried goat cheese, frisée lettuce',
      descriptionDe: '200g veganes Patty, gebratener Ziegenkäse, Friséesalat',
      price: 14.30,
      categoryId: veggie.id,
      imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Das Mauerblümchen',
      nameEn: 'The Wallflower',
      nameDe: 'Das Mauerblümchen',
      description: '200g veganes Patty, Champignons, Kidneybohnen, Friséesalat',
      descriptionEn: '200g vegan patty, mushrooms, kidney beans, frisée lettuce',
      descriptionDe: '200g veganes Patty, Champignons, Kidneybohnen, Friséesalat',
      price: 10.90,
      categoryId: veggie.id,
      imageUrl: 'https://images.unsplash.com/photo-1612198527556-aa397176c3f0?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Mediterraner Schmitzz',
      nameEn: 'Mediterranean Schmitzz',
      nameDe: 'Mediterraner Schmitzz',
      description: '200g veganes Patty, gegrillte Zucchini, Parmesan',
      descriptionEn: '200g vegan patty, grilled zucchini, Parmesan',
      descriptionDe: '200g veganes Patty, gegrillte Zucchini, Parmesan',
      price: 14.60,
      categoryId: veggie.id,
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
      isVegetarian: true,
    },

    // BEILAGEN
    {
      name: 'Schmitzz Fritten',
      nameEn: 'Schmitzz Fries',
      nameDe: 'Schmitzz Fritten',
      description: 'Knusprige Pommes Frites',
      descriptionEn: 'Crispy french fries',
      descriptionDe: 'Knusprige Pommes Frites',
      price: 3.60,
      categoryId: beilagen.id,
      imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Die Süsse Fritte',
      nameEn: 'The Sweet Fry',
      nameDe: 'Die Süsse Fritte',
      description: 'Süßkartoffel Pommes',
      descriptionEn: 'Sweet potato fries',
      descriptionDe: 'Süßkartoffel Pommes',
      price: 4.60,
      categoryId: beilagen.id,
      imageUrl: 'https://images.unsplash.com/photo-1502740479091-635887520276?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },

    // BUDDAH BOWLS
    {
      name: 'Vegan Bowl',
      nameEn: 'Vegan Bowl',
      nameDe: 'Vegan Bowl',
      description: 'Curry Couscous, Salatmix, Zucchini, Rotkraut, Hummus, Guacamole, Falafel',
      descriptionEn: 'Curry couscous, salad mix, zucchini, red cabbage, hummus, guacamole, falafel',
      descriptionDe: 'Curry Couscous, Salatmix, Zucchini, Rotkraut, Hummus, Guacamole, Falafel',
      price: 12.80,
      categoryId: bowls.id,
      imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Mexican Bowl',
      nameEn: 'Mexican Bowl',
      nameDe: 'Mexican Bowl',
      description: 'Vollkornreis, Salatmix, Chili con Carne, Parmesanchips, Guacamole',
      descriptionEn: 'Whole grain rice, salad mix, chili con carne, Parmesan chips, guacamole',
      descriptionDe: 'Vollkornreis, Salatmix, Chili con Carne, Parmesanchips, Guacamole',
      price: 13.50,
      categoryId: bowls.id,
      imageUrl: 'https://images.unsplash.com/photo-1546069901-eacef0df6022?w=800&q=80',
    },
    {
      name: 'Garnelen Bowl',
      nameEn: 'Shrimp Bowl',
      nameDe: 'Garnelen Bowl',
      description: 'Curry Couscous, Salatmix, gebratene Garnelen, Curry-Mango-Dip',
      descriptionEn: 'Curry couscous, salad mix, fried shrimp, curry-mango dip',
      descriptionDe: 'Curry Couscous, Salatmix, gebratene Garnelen, Curry-Mango-Dip',
      price: 14.60,
      categoryId: bowls.id,
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    },

    // DESSERTS
    {
      name: 'Käsekuchen',
      nameEn: 'Cheesecake',
      nameDe: 'Käsekuchen',
      description: 'Mit einer Kugel Vanilleeis und auf Wunsch mit Sahne',
      descriptionEn: 'With a scoop of vanilla ice cream and whipped cream on request',
      descriptionDe: 'Mit einer Kugel Vanilleeis und auf Wunsch mit Sahne',
      price: 5.30,
      categoryId: desserts.id,
      imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Schoko-Karamell-Walnussbrownie',
      nameEn: 'Chocolate-Caramel-Walnut Brownie',
      nameDe: 'Schoko-Karamell-Walnussbrownie',
      description: 'Mit einer Kugel Vanilleeis und auf Wunsch mit Sahne',
      descriptionEn: 'With a scoop of vanilla ice cream and whipped cream on request',
      descriptionDe: 'Mit einer Kugel Vanilleeis und auf Wunsch mit Sahne',
      price: 5.30,
      categoryId: desserts.id,
      imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80',
      isVegetarian: true,
    },

    // DRINKS
    {
      name: 'Watermelon-Schorle',
      nameEn: 'Watermelon Spritzer',
      nameDe: 'Watermelon-Schorle',
      description: 'Lemon Squash, Wassermelonensirup, Mangosirup, Soda (0,5L)',
      descriptionEn: 'Lemon squash, watermelon syrup, mango syrup, soda (0.5L)',
      descriptionDe: 'Lemon Squash, Wassermelonensirup, Mangosirup, Soda (0,5L)',
      price: 4.20,
      categoryId: drinks.id,
      imageUrl: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Coca-Cola',
      nameEn: 'Coca-Cola',
      nameDe: 'Coca-Cola',
      description: 'Erfrischende Cola (0,2L)',
      descriptionEn: 'Refreshing cola (0.2L)',
      descriptionDe: 'Erfrischende Cola (0,2L)',
      price: 3.20,
      categoryId: drinks.id,
      imageUrl: 'https://images.unsplash.com/photo-1510626176961-4b57d4fbad03?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Fritz Kola',
      nameEn: 'Fritz Kola',
      nameDe: 'Fritz Kola',
      description: 'Viel viel Koffein (0,2L)',
      descriptionEn: 'Lots and lots of caffeine (0.2L)',
      descriptionDe: 'Viel viel Koffein (0,2L)',
      price: 3.20,
      categoryId: drinks.id,
      imageUrl: 'https://images.unsplash.com/photo-1541971875078-28036ff16ee5?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Apfelsaft',
      nameEn: 'Apple Juice',
      nameDe: 'Apfelsaft',
      description: 'Frischer Apfelsaft (0,3L)',
      descriptionEn: 'Fresh apple juice (0.3L)',
      descriptionDe: 'Frischer Apfelsaft (0,3L)',
      price: 3.00,
      categoryId: drinks.id,
      imageUrl: 'https://images.unsplash.com/photo-1542444459-db68f1f1cf98?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Orangensaft',
      nameEn: 'Orange Juice',
      nameDe: 'Orangensaft',
      description: 'Frischer Orangensaft (0,3L)',
      descriptionEn: 'Fresh orange juice (0.3L)',
      descriptionDe: 'Frischer Orangensaft (0,3L)',
      price: 3.00,
      categoryId: drinks.id,
      imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Acqua Morelli Sprudel',
      nameEn: 'Acqua Morelli Sparkling',
      nameDe: 'Acqua Morelli Sprudel',
      description: 'Mineralwasser mit Kohlensäure (0,25L)',
      descriptionEn: 'Sparkling mineral water (0.25L)',
      descriptionDe: 'Mineralwasser mit Kohlensäure (0,25L)',
      price: 3.10,
      categoryId: drinks.id,
      imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },

    // BIER
    {
      name: 'Bayreuther Hell',
      nameEn: 'Bayreuther Hell',
      nameDe: 'Bayreuther Hell',
      description: 'Bayerisches helles Bier (0,5L)',
      descriptionEn: 'Bavarian lager beer (0.5L)',
      descriptionDe: 'Bayerisches helles Bier (0,5L)',
      price: 5.30,
      categoryId: bier.id,
      imageUrl: 'https://images.unsplash.com/photo-1527169402691-feff5539e52c?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Grevensteiner',
      nameEn: 'Grevensteiner',
      nameDe: 'Grevensteiner',
      description: 'Naturtrübes Landbier (0,5L)',
      descriptionEn: 'Naturally cloudy country beer (0.5L)',
      descriptionDe: 'Naturtrübes Landbier (0,5L)',
      price: 5.30,
      categoryId: bier.id,
      imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'San Miguel',
      nameEn: 'San Miguel',
      nameDe: 'San Miguel',
      description: 'Spanisches Lagerbier (0,5L)',
      descriptionEn: 'Spanish lager beer (0.5L)',
      descriptionDe: 'Spanisches Lagerbier (0,5L)',
      price: 5.10,
      categoryId: bier.id,
      imageUrl: 'https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Corona',
      nameEn: 'Corona',
      nameDe: 'Corona',
      description: 'Mexikanisches Bier (0,33L)',
      descriptionEn: 'Mexican beer (0.33L)',
      descriptionDe: 'Mexikanisches Bier (0,33L)',
      price: 3.90,
      categoryId: bier.id,
      imageUrl: 'https://images.unsplash.com/photo-1613478881950-0a5499a20e0a?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Maisels Weisse Original',
      nameEn: 'Maisels Weisse Original',
      nameDe: 'Maisels Weisse Original',
      description: 'Bayerisches Weißbier (0,5L)',
      descriptionEn: 'Bavarian wheat beer (0.5L)',
      descriptionDe: 'Bayerisches Weißbier (0,5L)',
      price: 5.20,
      categoryId: bier.id,
      imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },

    // WEIN
    {
      name: 'Chardonnay',
      nameEn: 'Chardonnay',
      nameDe: 'Chardonnay',
      description: 'Weißwein trocken (0,2L)',
      descriptionEn: 'Dry white wine (0.2L)',
      descriptionDe: 'Weißwein trocken (0,2L)',
      price: 4.90,
      categoryId: wein.id,
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Riesling',
      nameEn: 'Riesling',
      nameDe: 'Riesling',
      description: 'Weißwein halbtrocken (0,2L)',
      descriptionEn: 'Semi-dry white wine (0.2L)',
      descriptionDe: 'Weißwein halbtrocken (0,2L)',
      price: 6.90,
      categoryId: wein.id,
      imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Merlot',
      nameEn: 'Merlot',
      nameDe: 'Merlot',
      description: 'Rotwein halbtrocken (0,2L)',
      descriptionEn: 'Semi-dry red wine (0.2L)',
      descriptionDe: 'Rotwein halbtrocken (0,2L)',
      price: 4.60,
      categoryId: wein.id,
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Primitivo',
      nameEn: 'Primitivo',
      nameDe: 'Primitivo',
      description: 'Rotwein halbtrocken (0,2L)',
      descriptionEn: 'Semi-dry red wine (0.2L)',
      descriptionDe: 'Rotwein halbtrocken (0,2L)',
      price: 5.60,
      categoryId: wein.id,
      imageUrl: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },
    {
      name: 'Prosecco',
      nameEn: 'Prosecco',
      nameDe: 'Prosecco',
      description: 'Schaumwein herb (0,1L)',
      descriptionEn: 'Dry sparkling wine (0.1L)',
      descriptionDe: 'Schaumwein herb (0,1L)',
      price: 4.80,
      categoryId: wein.id,
      imageUrl: 'https://images.unsplash.com/photo-1513451713350-dee890297c4a?w=800&q=80',
      isVegetarian: true,
      isVegan: true,
    },

    // COCKTAILS
    {
      name: 'Aperol Spritz',
      nameEn: 'Aperol Spritz',
      nameDe: 'Aperol Spritz',
      description: 'Aperol, Prosecco, Soda (0,3L)',
      descriptionEn: 'Aperol, Prosecco, soda (0.3L)',
      descriptionDe: 'Aperol, Prosecco, Soda (0,3L)',
      price: 8.90,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Hugo',
      nameEn: 'Hugo',
      nameDe: 'Hugo',
      description: 'Holundersirup, Prosecco, Minze, Lime Juice (0,3L)',
      descriptionEn: 'Elderflower syrup, Prosecco, mint, lime juice (0.3L)',
      descriptionDe: 'Holundersirup, Prosecco, Minze, Lime Juice (0,3L)',
      price: 8.90,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Mojito',
      nameEn: 'Mojito',
      nameDe: 'Mojito',
      description: 'Weißer Rum, Limetten, Minze, Soda (0,3L)',
      descriptionEn: 'White rum, limes, mint, soda (0.3L)',
      descriptionDe: 'Weißer Rum, Limetten, Minze, Soda (0,3L)',
      price: 8.90,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Margarita Classic',
      nameEn: 'Classic Margarita',
      nameDe: 'Margarita Classic',
      description: 'Weißer Tequila, Triple Sec, Zitrone, Lime Juice (0,3L)',
      descriptionEn: 'White tequila, Triple Sec, lemon, lime juice (0.3L)',
      descriptionDe: 'Weißer Tequila, Triple Sec, Zitrone, Lime Juice (0,3L)',
      price: 8.90,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1609951651556-5334e2706168?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Piña Colada',
      nameEn: 'Piña Colada',
      nameDe: 'Piña Colada',
      description: 'Ananas, Coconut Cream, Sahne, weißer Rum (0,3L)',
      descriptionEn: 'Pineapple, coconut cream, cream, white rum (0.3L)',
      descriptionDe: 'Ananas, Coconut Cream, Sahne, weißer Rum (0,3L)',
      price: 8.90,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Sex on the Beach',
      nameEn: 'Sex on the Beach',
      nameDe: 'Sex on the Beach',
      description: 'Vodka, Peach Likör, Lemon Squash, Orange (0,3L)',
      descriptionEn: 'Vodka, peach liqueur, lemon squash, orange (0.3L)',
      descriptionDe: 'Vodka, Peach Likör, Lemon Squash, Orange (0,3L)',
      price: 8.90,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800&q=80',
      isVegetarian: true,
    },
    {
      name: 'Long Island Ice Tea',
      nameEn: 'Long Island Ice Tea',
      nameDe: 'Long Island Ice Tea',
      description: 'Rum, Vodka, Gin, Triple Sec, Tequila, Coca-Cola (0,5L)',
      descriptionEn: 'Rum, vodka, gin, Triple Sec, tequila, Coca-Cola (0.5L)',
      descriptionDe: 'Rum, Vodka, Gin, Triple Sec, Tequila, Coca-Cola (0,5L)',
      price: 15.00,
      categoryId: cocktails.id,
      imageUrl: 'https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?w=800&q=80',
      isVegetarian: true,
    },
  ];

  // Delete existing menu items to ensure fresh data
  logger.info('Deleting existing menu items...');
  await prisma.menuItem.deleteMany({});

  logger.info('Creating menu items...');
  for (const item of menuItems) {
    await prisma.menuItem.create({
      data: item,
    });
  }

  // Create default settings
  logger.info('Creating default settings...');
  const minOrderValue = await prisma.settings.findUnique({
    where: { key: 'minOrderValue' }
  });
  if (!minOrderValue) {
    await prisma.settings.create({
      data: {
        key: 'minOrderValue',
        value: '10.00',
        description: 'Minimum order value in EUR'
      }
    });
  }

  logger.info('✅ Database seeded successfully!');
  logger.info(`Created ${categories.length} categories`);
  logger.info(`Created ${menuItems.length} menu items`);
}

main()
  .catch((e) => {
    logger.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
